### ISSUE TITLE
Slapper's skin

### ISSUE THREAD

**Issue by ghost** [PMPlugins/Complete-Plugins#1]
How to change sender's skin to player's skin? I dont know coding, could you help me :)

**Comment by legoboy0215** [comment]
See SkinTools.

**Comment by ghost** [comment]
No. like the one in PigRaid server, players look at slapper and see their skin on it

**Comment by legoboy0215** [comment]
I have that plugin. It is by the PigRaid owner :)

**Comment by legoboy0215** [comment]
I will try to implement it into Slapper.

**Comment by ghost** [comment]
Thank you :)

**Comment by ghost** [comment]
Could you share? :v

**Comment by legoboy0215** [comment]
Share the code? No, I will just put it in Slapper :P

**Comment by ghost** [comment]
Ok, i understand :)
